/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'AsmLab' 
 * Target:  'Target 1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* ARM::CMSIS:RTOS2:Keil RTX5&Library@5.5.4 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
/* Keil::Device:STM32Cube HAL:ADC@1.0.2 */
#define RTE_DEVICE_HAL_ADC
/* Keil::Device:STM32Cube HAL:Common@1.0.0 */
#define RTE_DEVICE_HAL_COMMON
/* Keil::Device:STM32Cube HAL:Cortex@1.0.2 */
#define RTE_DEVICE_HAL_CORTEX
/* Keil::Device:STM32Cube HAL:DMA@1.0.2 */
#define RTE_DEVICE_HAL_DMA
/* Keil::Device:STM32Cube HAL:EXTI@1.0.2 */
#define RTE_DEVICE_HAL_EXTI
/* Keil::Device:STM32Cube HAL:Flash@1.0.2 */
#define RTE_DEVICE_HAL_FLASH
/* Keil::Device:STM32Cube HAL:GPIO@1.0.2 */
#define RTE_DEVICE_HAL_GPIO
/* Keil::Device:STM32Cube HAL:I2C@1.0.2 */
#define RTE_DEVICE_HAL_I2C
/* Keil::Device:STM32Cube HAL:PWR@1.0.2 */
#define RTE_DEVICE_HAL_PWR
/* Keil::Device:STM32Cube HAL:RCC@1.0.2 */
#define RTE_DEVICE_HAL_RCC
/* Keil::Device:STM32Cube HAL:TIM@1.0.2 */
#define RTE_DEVICE_HAL_TIM
/* Keil::Device:STM32Cube HAL:UART@1.0.2 */
#define RTE_DEVICE_HAL_UART
/* Keil::Device:STM32Cube HAL:USART@1.0.2 */
#define RTE_DEVICE_HAL_USART
/* Keil::Device:Startup@1.0.2 */
#define RTE_DEVICE_STARTUP_STM32L5XX    /* Device Startup for STM32L5 */


#endif /* RTE_COMPONENTS_H */
