/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'IntDemo' 
 * Target:  'Target 1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32l5xx.h"

/* Keil::Device:STM32Cube HAL:Common@1.0.0 */
#define RTE_DEVICE_HAL_COMMON
/* Keil::Device:STM32Cube HAL:Cortex@1.0.2 */
#define RTE_DEVICE_HAL_CORTEX
/* Keil::Device:STM32Cube HAL:DMA@1.0.2 */
#define RTE_DEVICE_HAL_DMA
/* Keil::Device:STM32Cube HAL:Flash@1.0.2 */
#define RTE_DEVICE_HAL_FLASH
/* Keil::Device:STM32Cube HAL:GPIO@1.0.2 */
#define RTE_DEVICE_HAL_GPIO
/* Keil::Device:STM32Cube HAL:PWR@1.0.2 */
#define RTE_DEVICE_HAL_PWR
/* Keil::Device:STM32Cube HAL:RCC@1.0.2 */
#define RTE_DEVICE_HAL_RCC
/* Keil::Device:STM32Cube HAL:TIM@1.0.2 */
#define RTE_DEVICE_HAL_TIM
/* Keil::Device:Startup@1.0.2 */
#define RTE_DEVICE_STARTUP_STM32L5XX    /* Device Startup for STM32L5 */


#endif /* RTE_COMPONENTS_H */
